import { describe, expect, it } from 'vitest';
import { generateWorkflowManagementHtml } from './workflows-ui.js';
import workflowsSetup from './workflows-ui.mjs?raw';

describe('workflow management UI', () => {
  it('provides authenticated workflow and write-only secret controls', () => {
    const html = generateWorkflowManagementHtml('editor', 'example');
    const source = html + workflowsSetup;

    expect(source).toContain('<code-editor');
    expect(source).toContain('id="source-yaml"');
    expect(source).toContain('https://sodium.static.apphor.de/code-editor.html');
    expect(source).toContain('https://sodium.static.apphor.de/code-block.html');
    expect(source).toContain('https://sodium.static.apphor.de/lucide-icon.html');
    expect(source).toContain('<template app>');
    expect(source).toContain('/api/workflows/validate');
    expect(source).toContain('Save draft');
    expect(source).toContain('href="/workflows/new"');
    expect(source).not.toContain('aria-label="Workflow count"');
    expect(source).toContain('text-base font-semibold text-gray-100');
    expect(source).toContain('type="checkbox"');
    expect(source).toContain('bind-checked="enabled"');
    expect(source).toContain('bind-disabled="selectedId"');
    expect(source).toContain('The ID becomes permanent after the first save.');
    expect(source).toContain('No changes to save.');
    expect(source).toContain('setTimeout(() =>');
    expect(source).toContain('validation.value = { ...validation.value, running: true, error: \'\' }');
    expect(source).toContain("validation.value = { valid: false, running: false, error: error.message }");
    expect(source).toContain('hidden sm:inline');
    expect(source).toContain('Workflow revision {{ revisionNumber }}');
    expect(source).toContain('on-click="navigateRevision(-1)"');
    expect(source).toContain('bind-innerhtml="revisionDiffHtml"');
    expect(source).toContain('https://unpkg.com/diff@9.0.0/libesm/index.js');
    expect(source).toContain('Get AI workflow help');
    expect(source).toContain('/api/ai/workflow-help');
    expect(source).toContain('Accept suggestion');
    expect(source).toContain('aria-label="Save workflow draft"');
    expect(source).toContain('bind-disabled="busy || !selectedId || source !== savedSource || enabled !== savedEnabled"');
    expect(source).toContain('aria-labelledby="workflow-list-title"');
    expect(source).toContain('attr-href="\'/workflows/\' + workflow.id"');
    expect(source).toContain('href="/workflows"');
    expect(source).toContain('Back to workflows');
    expect(source).toContain('<app-header');
    expect(source).toContain('href="/app-header.html"');
    expect(source).toContain('ref="helpContent"');
    expect(source).toContain('on-toggle="loadHelp($event)"');
    expect(source).toContain('new DOMParser()');
    expect(source).not.toContain('<iframe');
    expect(source).toContain('focus-visible:ring-2');
    expect(source).toContain('Publish');
    expect(source).toContain('/api/workflows/');
    expect(source).toContain('Run workflow now');
    expect(source).toContain('runNow');
    expect(source).toContain('/api/secrets/');
    expect(source).toContain('type="password"');
    expect(source).toContain('type="file"');
    expect(source).toContain('Binary file secret');
    expect(source).toContain('bind-checked="fileMode"');
    expect(source).toContain('encoding: \'base64\'');
    expect(source).toContain('on-click="removeSecret(name)"');
    expect(source).toContain('aria-label="Delete secret {{ name }}"');
    expect(source).toContain('ref="secretForm"');
    expect(source).toContain('Add a secret');
    expect(source).toContain('icon="trash"');
    expect(source).toContain('aria-label="Saved secrets"');
    expect(source).toContain('aria-label="Edit secret {{ name }}"');
    expect(source).toContain('data-page="editor"');
    expect(source).toContain("const initialId = params.get('id') || ''");
    expect(source).toContain("const initialRevision = params.get('revision') ? Number(params.get('revision')) : null");
  });
});
